# Change these first comentario para que vuelva a crear
owner: nachosalvi # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Aysa Sitio Corporativo
    url: https://www.aysa.com.ar
    __dangerous__disable_verify_peer: true
  - name: Aysa Intranet
    url: https://intranet.aysa.com.ar/login
  - name: Aysa ServiceDesk
    url: https://servicedesk.aysa.com.ar
  #- name: Aysa Encuestas
  #  url: https://encuestas.aysa.com.ar
  - name: Aysa Oficina Virtual
    url: https://oficinavirtual.web.aysa.com.ar/index.html
    __dangerous__disable_verify_peer: true
  - name: Aysa Mail
    url: https://mail.aysa.com.ar
    __dangerous__disable_verify_peer: true
Assignees:
  - nachosalvi

status-website:
  # bAdd your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AySA Status Site
  introTitle: "Sitio de disponibilidad servicios web AySA S.A."
  introMessage: Gerencia de Servicios Informaticos / Soporte Aplicativos
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
i18n:
  footer: Powered by [AySA S.A.](https://www.aysa.com.ar)      

# cUpptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
